image: golang

#variables:
#  CI_PROJECT_DIR: /go/src/gitlab.com/terraform-provider-sewan

stages:
#  - gofmt
#  - test
  - sonar

#gofmt:
#  stage: gofmt
#  script:
#    - gofmt -w $(find . -name '*.go')

#tests:
#  stage: test
#  before_script:
#        # Create a symbolic link under $GOPATH, this is needed for local build
#    # i.e. /go/src/gitlab.com/ykyuen/gitlab-ci-go-build
#    - cd $GOPATH/src
#    - mkdir -p gitlab.com/$CI_PROJECT_NAMESPACE
#    - cd gitlab.com/$CI_PROJECT_NAMESPACE
#    - ln -s $CI_PROJECT_DIR
#    - cd $CI_PROJECT_NAME
#    - pwd
#    - cd ../
#    - mkdir /go/src/gitlab.com
#    - ls -al /go/src/gitlab.com
#    - git clone https://github.com/SewanDevs/sewan_go_sdk.git \
#        /go/src/gitlab.com/sewan_go_sdk
#    - ls -al /go/src/gitlab.com
#    - ls -al /go/src/gitlab.com/sewan_go_sdk
#    - go get github.com/hashicorp/terraform/helper/schema
#    - go get github.com/hashicorp/terraform/terraform
#    - go get ./terraform-provider-sewan/sewan
#    - ls -al /go/src/gitlab.com/
#    - ls -al /go/src/github.com/
#    - ls -al /go/src/github.com/hashicorp
#  script:
#    - go test -coverprofile=coverage.out
#    - go test -json > report.json
#    - go tool cover -html=c.out -o coverage.html

sonarqube_preview:
  image: $DOCKER_REGISTRY/sidevops/docker/utils/sonar-ci:latest
  stage: sonar
  script:
    - sh /opt/sonar-runner/bin/sonar-runner
      -Dsonar.host.url=$SONAR_URL
      -Dsonar.gitlab.user_token=$SONAR_GITLAB_USERTOKEN
      -Dsonar.login=$SONAR_LOGIN
      -Dsonar.gitlab.project_id=$CI_PROJECT_PATH
      -Dsonar.analysis.mode=preview
      -Dsonar.issuesReport.console.enable=true
      -Dsonar.gitlab.commit_sha=$CI_BUILD_REF
      -Dsonar.gitlab.ref_name=$CI_BUILD_REF_NAME

sonarqube:
  image: $DOCKER_REGISTRY/sidevops/docker/utils/sonar-ci:latest
  stage: sonar
  script:
    - sh /opt/sonar-runner/bin/sonar-runner
      -Dsonar.host.url=$SONAR_URL
      -Dsonar.login=$SONAR_LOGIN
