image: golang

#variables:
#  CI_PROJECT_DIR: /go/src/gitlab.com/terraform-provider-sewan

stages:
#  - gofmt
  - test
  - sonar

#gofmt:
#  stage: gofmt
#  script:
#    - gofmt -w $(find . -name '*.go')

tests:
  stage: test
  before_script:
    #- mkdir /go/src/github.com/
    #- mkdir /go/src/github.com/hashicorp/
    - go get github.com/hashicorp/terraform/helper/schema
    #- git version
    #- git clone https://github.com/hashicorp/terraform.git \
    #  /go/src/github.com/hashicorp/
    - ls -al /go/src/
    - ls -al /go/src/github.com
    - ls -al /go/src/github.com/hashicorp/
    - ls -al /go/src/github.com/hashicorp/terraform

  script:
    - pwd
    - ls -al
    - go test -coverprofile=coverage.out
    - go test -json > report.json
    #- go tool cover -html=coverage.out -o coverage.html

sonarqube_preview:
  image: $DOCKER_REGISTRY/sidevops/docker/utils/sonar-ci:latest
  stage: sonar
  script:
    - sh /opt/sonar-runner/bin/sonar-runner \
      -Dsonar.host.url=$SONAR_URL \
      -Dsonar.gitlab.user_token=$SONAR_GITLAB_USERTOKEN \
      -Dsonar.login=$SONAR_LOGIN \
      -Dsonar.gitlab.project_id=$CI_PROJECT_PATH \
      -Dsonar.analysis.mode=preview \
      -Dsonar.issuesReport.console.enable=true \
      -Dsonar.gitlab.commit_sha=$CI_BUILD_REF \
      -Dsonar.gitlab.ref_name=$CI_BUILD_REF_NAME

sonarqube:
  image: $DOCKER_REGISTRY/sidevops/docker/utils/sonar-ci:latest
  stage: sonar
  script:
    - sh /opt/sonar-runner/bin/sonar-runner \
     -Dsonar.host.url=$SONAR_URL \
     -Dsonar.login=$SONAR_LOGIN
