package sewan_go_sdk

const (
	NAME_FIELD          = "name"
	ENTERPRISE_FIELD    = "enterprise"
	DATACENTER_FIELD    = "datacenter"
	VDC_RESOURCE_FIELD  = "vdc_resources"
	RESOURCE_FIELD      = "resource"
	TOTAL_FIELD         = "total"
	USED_FIELD          = "used"
	SLUG_FIELD          = "slug"
	STATE_FIELD         = "state"
	OS_FIELD            = "os"
	RAM_FIELD           = "ram"
	CPU_FIELD           = "cpu"
	DISKS_FIELD         = "disks"
	SIZE_FIELD          = "size"
	STORAGE_CLASS_FIELD = "storage_class"
	DELETION_FIELD      = "deletion"
	NICS_FIELD          = "nics"
	VLAN_NAME_FIELD     = "vlan"
	MAC_ADRESS_FIELD    = "mac_address"
	CONNECTED_FIELD     = "connected"
	VDC_FIELD           = "vdc"
	BOOT_FIELD          = "boot"
	TOKEN_FIELD         = "token"
	BACKUP_FIELD        = "backup"
	DISK_IMAGE_FIELD    = "disk_image"
	PLATFORM_NAME_FIELD = "platform_name"
	BACKUP_SIZE_FIELD   = "backup_size"
	COMMENT_FIELD       = "comment"
	TEMPLATE_FIELD      = "template"
	ID_FIELD            = "id"
	DYNAMIC_FIELD       = "dynamic_field"
)
